# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
font_size 12.0
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

# Quality of life
scrollback_lines 20000
cursor_shape beam

# Deafult shell
shell fish

# Window spacing (Hyprland-friendly)
window_padding_width 8

# Key maps
map ctrl+f      launch --location=hsplit --allow-remote-control kitty +kitten kitty-kitten-search/search.py @active-kitty-window-id

scrollback_pager bash -c "exec nvim 63<&0 0</dev/null -u NONE -c 'map <silent> q :qa!<CR>' -c 'set shell=bash scrollback=100000 termguicolors laststatus=0 clipboard+=unnamedplus' -c 'autocmd TermOpen * setlocal number' -c 'autocmd TermEnter * stopinsert' -c 'terminal cat /dev/fd/63' -c 'autocmd TermClose * normal G'"

# TERM
term xterm-kitty
