#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = uwsm-app -- quickshell -c volcmen # Status bar
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- hyprpaper # Wallpaper
exec-once = uwsm-app -- /usr/lib/polkit-kde-authentication-agent-1 # Polkit agent, popup for password

# Clipboard history
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store # Stores only text data
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store # Stores only image data


# Final Cleanup (Optional but good)
exec-shutdown = uwsm stop
