###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = $terminal -e yazi; exit 
$menu = fuzzel
$browser = zen-browser

# Set modifiers
$mainMod = SUPER # Sets "Windows" key as main modifier
$hyperMod = SUPER CTRL ALT SHIFT # Sets "Hyper" key as modifier

# Keybinds for applications
bind = $mainMod, SPACE, exec, uwsm-app -- $menu
bind = $hyperMod, T, exec, uwsm-app -- $terminal
bind = $hyperMod, F, exec, uwsm-app -- $fileManager
bind = $hyperMod, B, exec, uwsm-app -- $browser

# Control scratchpad
bindd = SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER ALT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

# Bind to change language 
binddl = $hyperMod, Space, Change language, exec, hyprctl switchxkblayout all next

bind = Super+Shift, S, global, quickshell:regionScreenshot # Screen snip

source= ~/.config/hypr/hyprland/bindings/clipboard.conf
source= ~/.config/hypr/hyprland/bindings/groups.conf
source= ~/.config/hypr/hyprland/bindings/media.conf
source= ~/.config/hypr/hyprland/bindings/mouse.conf
source= ~/.config/hypr/hyprland/bindings/tiling.conf
