$text_color = rgba(d9e2ffFF)
$entry_background_color = rgba(00194411)
$entry_border_color = rgba(33ccffee) rgba(00ff99ee) 45deg
$entry_color = rgba(d9e2ffFF)
$font_family = Google Sans Flex Medium
$font_family_clock = Google Sans Flex Medium

background {
    color = rgba(181818FF)
}
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $entry_background_color

    outer_color = $entry_border_color
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $entry_color
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = $text_color
    font_size = 14
    font_family = $font_family
    position = -30, 30
    halign = right
    valign = bottom
}

label { # Clock
    monitor =
    text = $TIME12
    color = $text_color
    font_size = 65
    font_family = $font_family_clock

    position = 0, 300
    halign = center
    valign = center
}
label { # Date
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = $text_color
    font_size = 17
    font_family = $font_family_clock

    position = 0, 240
    halign = center
    valign = center
}
