# Clipboard Copy / Paste
bindd = $mainMod, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = $mainMod, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = $mainMod, X, Universal cut, sendshortcut, CTRL, X,
bindd = $mainMod CTRL, V, Clipboard manager, exec, cliphist list | $menu --dmenu --with-nth 2 | cliphist decode | wl-copy # Clipboard manager for Fuzzel